### ISSUE TITLE
TODO: Figure out imports

### ISSUE THREAD

**Issue by mpavlak2018** [pingryiRT/ChatInterface#1]
**TODO: on line 7 of Main:**
We need to figure out how we will change the imports to allow for our new structure with the P2P platform and Interface separation.

**Comment by jorndorff** [comment]
It should be as easy as changing the lines from
```
from Network import Network
from Peer import Peer
```
to 
```
from p2p-platform import Network
from p2p-platform import Peer
```

**Comment by jorndorff** [comment]
The one trick is you'll have to make sure p2p-platform is installed and on your $PYTHONPATH Let's chat about that in person sometime. Stop by the tech office or maybe after tomorrow's meeting.

**Comment by mpavlak2018** [comment]
I know we fixed this, but we might want to put it into the readme...

**Comment by jorndorff** [comment]
I've included this in the readme on the stripdown branch.
