### ISSUE TITLE
TODO: Formalize XML

### ISSUE THREAD

**Issue by mpavlak2018** [pingryiRT/ChatInterface#2]
**TODO: Line 16 of Main.** 
We need to formalize our XML for message passing (to be put into tag dict).
We also need to talk about whether or not this should be predominantly defined in Network (I personally believe it should be)

**Comment by jorndorff** [comment]
Yeah, this seems like something that should be mostly in network, or at least in the P2P Platform project.

**Comment by jorndorff** [comment]
Sounds like we're in agreement that this should happen in the P2PPlatform, and now that master is the most active branch over there, I think we're good to go.
