### ISSUE TITLE
TODO: Move network level threads

### ISSUE THREAD

**Issue by mpavlak2018** [pingryiRT/ChatInterface#3]
**TODO: Line 37 of main**
Try to see if we can move the receiver thread and acceptor thread, and their starts, into the network's __init__. I think it would be a neater solution (this way, although all threads are not started in the same place, an end user would not have to worry as much about network end threading)

**Comment by jorndorff** [comment]
The code you're referring to is commented out as far as I can tell and I believe that move has been made. I'm going to close this for now, but reopen if I misunderstood the issue.
