### ISSUE TITLE
TODO: Allow interface only shutdown

### ISSUE THREAD

**Issue by mpavlak2018** [pingryiRT/ChatInterface#6]
**TODO: Line 35 of Interface**
We should probably make an option to allow the interface to close while keeping the network running. This might involve more complex work with the threads though.

**Comment by jorndorff** [comment]
We should figure out the scope of this ChatClient project together. I totally agree that the P2PPlatform should support "headless" mode (running without a user interface attached).

I question whether it's the best use of our time in the ChatClient though.

**Comment by jorndorff** [comment]
Actually, running headless might make a lot of sense in the distributed network where long-running programs may need to be left unattended in the background. What do you think about moving this issue over there in the spirit of making ChatClient a relatively easy-to-maintain codebase that we can use for primarily for testing the distributed network.

**Comment by jorndorff** [comment]
Oops, didn't mean to close.

**Comment by jorndorff** [comment]
@mpavlak2018 I'm closing this because I moved it over to https://github.com/pingryiRT/DistributedNetwork/issues/1 See above for why and please re-open if you want this feature here too.

**Comment by jorndorff** [comment]
Oh, and actually, this is starting to happen naturally. For example more code could be run on the network after the interface shuts down around line 181 in Interface.
